### ISSUE TITLE
Requested Windows Runtime type 'VideoEffects.LumiaAnalyzerDefinition' is not registered.

### ISSUE THREAD

**Issue by saprile** [mmaitre314/VideoEffect#12]
When try to integrate your QR realtime code in my app, this is a error. I'm crazy to solve this

**Comment by mmaitre314** [comment]
Maybe an issue in the AppxManifest.xml file created during the build (especially if this is a C++ app). Do you have something like the following in that file (with VideoEffects.LumiaAnalyzerDefinition, etc.)?

  <Extensions>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>VideoEffects.Windows.dll</Path>
        <ActivatableClass ActivatableClassId="VideoEffects.LumiaEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="VideoEffects.LumiaAnalyzer" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="VideoEffects.ShaderEffectBgrx8" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="VideoEffects.ShaderEffectNv12" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="VideoEffects.SquareEffect" ThreadingModel="both" />
      </InProcessServer>
    </Extension>
  </Extensions>

AppxManifest.xml is in the same folder as your EXE.

**Comment by saprile** [comment]
this is my appxmanifest (in windows phone 8.1)
  
<Extensions>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>VideoEffects.WindowsPhone.dll</Path>
        <ActivatableClass ActivatableClassId="VideoEffects.CanvasEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="VideoEffects.LumiaEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="VideoEffects.LumiaAnalyzer" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="VideoEffects.ShaderEffectBgrx8" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="VideoEffects.ShaderEffectNv12" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="VideoEffects.SquareEffect" ThreadingModel="both" />
      </InProcessServer>
    </Extension>
  </Extensions>

**Comment by mmaitre314** [comment]
There are two similar files: Package.appxmanifest (in the source code) and AppxManifest.xml (in the output of the build). Could you check the latter? It should have a lot of <ActivatableClass> coming from VideoEffects.WindowsPhone.dll, Lumia.Imaging.dll, Lumia.InteropServices.WindowsRuntime.dll, CLRHost.dll, and Microsoft.Graphics.Canvas.dll.

![capture](https://cloud.githubusercontent.com/assets/8584604/7538119/a50734e6-f552-11e4-9bcb-37a345e65c98.PNG)

If that does not lead to any meaningful info, would you be able to provide a VS project with a minimal repro?

**Comment by saprile** [comment]
The is my extension section http://1drv.ms/1H3QFfp

the  Lumia.Imaging.dll, Lumia.InteropServices.WindowsRuntime.dll are present in output folder but the 
CLRHost.dll, Microsoft.Graphics.Canvas.dll and VideoEffects.WindowsPhone.dll there are not present. 

What 's happened ? 
Why this libraries do not included in the package ?

Do I wrong somethign ?
I've used a nuget to set the reference.

Thanks

**Comment by mmaitre314** [comment]
Ok, so the extension XML looks fine. There is no Microsoft.Graphics.Canvas.dll there so I assume you are using a version of VideoEffect slightly older than the latest, which should be fine. I am wondering if NuGet failed to properly update the VS project csproj file when installing VideoEffect. Could you try uninstalling the VideoEffect NuGet and Lumia, etc. if they are still there, manually deleting those packages from the packages\ folder if they did not get automatically removed, and then reinstalling the VideoEffect NuGet? If that does not work, could you share you .csproj file? I can check if NuGet properly injected the references. I have seen it get that wrong before.

**Comment by saprile** [comment]
I've removed, clear and readded the library from nuget but the dlls not are present. this is my project http://1drv.ms/1EWFu7F.

I've used the 2.3.0.0 (latest versione of nuget)

**Comment by saprile** [comment]
I think to have found the issue.

The path reference of the VideoEffects.WindowsPhone dll in my project is 

...\packages\MMaitre.VideoEffects.2.3.0\build\wpa81\\..\Native\WindowsPhone\ARM\VideoEffects.winmd

and this is wrong because the there is a \\ betwen wpa81 e native (wpa81\\..\Native) . This configuration is taken from 

..packages\MMaitre.VideoEffects.2.3.0\build\wpa81\MMaitre.VideoEffects.targets

If you open this file there is a HintPath :

$(MSBuildThisFileDirectory)\..\Native\WindowsPhone\$(PlatformTarget)\VideoEffects.winmd

but according to me the correct path should be

$(MSBuildThisFileDirectory)..\Native\WindowsPhone\$(PlatformTarget)\VideoEffects.winmd

**Comment by saprile** [comment]
the same issue is presenti for the libs:

Lumia.Imaging
Lumia.Imaging.Managed
Lumia.InteropServices.WindowsRuntime

**Comment by saprile** [comment]
I've try to copy the right dlls into output folder, but not run.

Could be create a new project that use nuget and that use QRCode detector (the same of the your example) ?

**Comment by mmaitre314** [comment]
Mystery. The double \ should be ok: it is treated as a single one (afaik).

I tried to create some basic app, see if that could reproduce the issue:

- Create a new "Blank App (Windows Phone)" project
- Add two NuGet packages: Json.NET (used as reference) and Video Effects
- Add some basic code in OnNavigatedTo:

```C#
protected override void OnNavigatedTo(NavigationEventArgs e)
{
    var obj = new Newtonsoft.Json.Linq.JObject();

    var def = new VideoEffects.LumiaAnalyzerDefinition(Lumia.Imaging.ColorMode.Gray8, 640, (bitmap, time) =>
    {
    });

    System.Diagnostics.Debugger.Break();
}
```
- Run under the debugger in the Phone emulator and see what happens

When I ran both the JObject and LumiaAnalyzerDefinition objects were created fine and the break point was hit.

Could you try something like that on your machine, see if you hit an issue?

**Comment by saprile** [comment]
your example app run succesfully but my app no. I'm crazy and therefore I've follow another approach.

If you want, I avalible to solve this issue and to help you to do this

**Comment by LanceMcCarthy** [comment]
I've seen this error when removing an older C++ MFT (a RuntimeComponent I had built and was part of the solution) after I had already added VideoEffects.

After inspecting the manifest, I seen that VideoEffects' install script added the ActivatibleClasses to my existing MFT Extension. So what I ended up with was two copies of the VideoEffects ActivatibleClasses: one in my extension and one where it is supposed to be (the VideoEffect's Extension).

The funny part here is that it worked. When calling for an ActivatibleClass, it was consumed properly by the Media Capture. However, when I removed my MFT and left only your (much better) one and tried to consume the ActivatibleClass, it would fail with this error.

I have code and more details here: https://social.msdn.microsoft.com/Forums/windowsapps/en-US/fd01b273-1514-44f9-9510-aed434abe12d/wp81inprocessserver-and-mixed-up-activatibleclasses?forum=wpdevelop 

I have James Dailey(MS) and Raman Shar.(MS) looking at the full code now, but if this is related to this Nuget package, I can send you the repo as well.

**Comment by mmaitre314** [comment]
Thanks for the heads up! That sounds like a bug in the custom XML transforms use in the library or in the way NuGet applies those transforms. The library merges a chunk of XML to register the MFTs during package install:
https://github.com/mmaitre314/VideoEffect/blob/master/VideoEffects/Package/Package.appxmanifest.wpa81.transform
I don't understand why uninstalling something would cause that chunk of XML to be re-added, and at the wrong location, but it looks like NuGet also supports XDT transforms which should allow more precise XML addition/deletion. I'll go through the NuGet docs and give it a try.

**Comment by mmaitre314** [comment]
Just to keep the thread updated, the extra-XML issue was fixed but the registration issue remains. There is some incompatibility with MS Ads. After adding MS Ads the GenerateAppxManifest MSBuild task does not see constructors in VideoEffects.winmd anymore.

**Comment by mmaitre314** [comment]
This is a known bug in Visual Studio that was fixed but not released yet. In the meantime the work around is to add the registration info directly into Package.appxmanifest:

```xml
<Extension Category="windows.activatableClass.inProcessServer">
  <InProcessServer>
    <Path>VideoEffects.Windows.dll</Path>
    <ActivatableClass ActivatableClassId="VideoEffects.CanvasEffect" ThreadingModel="both"/>
    <ActivatableClass ActivatableClassId="VideoEffects.LumiaEffect" ThreadingModel="both"/>
    <ActivatableClass ActivatableClassId="VideoEffects.LumiaAnalyzer" ThreadingModel="both"/>
    <ActivatableClass ActivatableClassId="VideoEffects.ShaderEffectBgrx8" ThreadingModel="both"/>
    <ActivatableClass ActivatableClassId="VideoEffects.ShaderEffectNv12" ThreadingModel="both"/>
    <ActivatableClass ActivatableClassId="VideoEffects.SquareEffect" ThreadingModel="both"/>
    <ActivatableClass ActivatableClassId="VideoEffects.LumiaEffectDefinition" ThreadingModel="both"/>
  </InProcessServer>
</Extension>
<Extension Category="windows.activatableClass.inProcessServer">
  <InProcessServer>
    <Path>Lumia.Imaging.dll</Path>
    <ActivatableClass ActivatableClassId="Lumia.Imaging.Bitmap" ThreadingModel="both" />
    <ActivatableClass ActivatableClassId="Lumia.Imaging.BitmapImageSource" ThreadingModel="both" />
  </InProcessServer>
</Extension>
```

**Comment by shoareuk** [comment]
Hi, I'm getting the same issue running it on Windows Phone 8.1 RT. I added the above extensions (changing to VideoEffects.WindowsPhone.dll). Any thoughts?

**Comment by mmaitre314** [comment]
Are you using Win2D effects by any chance? There is a similar patch needed for that. You can check what appears in AppxManifest.xml in the build folder. There I believe the extra patch in Package.appxmanifest is:

```xml
<Extension Category="windows.activatableClass.inProcessServer">
  <InProcessServer>
    <Path>Microsoft.Graphics.Canvas.dll</Path>
    <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.CanvasBitmap" ThreadingModel="both" />
  </InProcessServer>
</Extension>
```

**Comment by shoareuk** [comment]
Thanks for the quick response. I tried adding that, still the same. I created a new empty WP 8.1 RT project and added the NuGet package and added the following line:

'var definition = new VideoEffects.LumiaAnalyzerDefinition(Lumia.Imaging.ColorMode.Yuv420Sp, 640, (b, t) => { });'

And that processes fine.  I compared the Package.appmanifest and it has only:

'<Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>VideoEffects.WindowsPhone.dll</Path>
        <ActivatableClass ActivatableClassId="VideoEffects.CanvasEffect" ThreadingModel="both"/>
        <ActivatableClass ActivatableClassId="VideoEffects.LumiaEffect" ThreadingModel="both"/>
        <ActivatableClass ActivatableClassId="VideoEffects.LumiaAnalyzer" ThreadingModel="both"/>
        <ActivatableClass ActivatableClassId="VideoEffects.ShaderEffectBgrx8" ThreadingModel="both"/>
        <ActivatableClass ActivatableClassId="VideoEffects.ShaderEffectNv12" ThreadingModel="both"/>
        <ActivatableClass ActivatableClassId="VideoEffects.SquareEffect" ThreadingModel="both"/>
      </InProcessServer>
    </Extension>'

The rest of the code is much the same as your QRCode example in the solution for the time being

**Comment by mmaitre314** [comment]
The bug actually shows up in AppxManifest.xml (the file that gets generated during the build from the Package.appxmanifest template). It should be in your bin folder along with your app. The fix is to add the missing XML in Package.appxmanifest so it ends up in AppxManifest.xml (basically adding what the build process was supposed to add on its own).

**Comment by shoareuk** [comment]
Ahh I was comparing the wrong file, added a couple of Extensions with whole raft of ActivatableClass and that seems to have done the trick. Thanks for the pointers :+1:

**Comment by Sorcha** [comment]
Hi,

I using this library for a barcode scanner. Until today, everthing was fine. The problem is when I install the packge Google Analytics SDK for Windows 8 and Windows Phone. I getting this error  'VideoEffects.LumiaAnalyzerDefinition' is not registered.
My project is a universal app. 
Can you helping? 
My Package.appxmanifest have

  <Extensions>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>VideoEffects.WindowsPhone.dll</Path>
        <ActivatableClass ActivatableClassId="VideoEffects.CanvasEffect" ThreadingModel="both"/>
        <ActivatableClass ActivatableClassId="VideoEffects.LumiaEffect" ThreadingModel="both"/>
        <ActivatableClass ActivatableClassId="VideoEffects.LumiaAnalyzer" ThreadingModel="both"/>
        <ActivatableClass ActivatableClassId="VideoEffects.ShaderEffectBgrx8" ThreadingModel="both"/>
        <ActivatableClass ActivatableClassId="VideoEffects.ShaderEffectNv12" ThreadingModel="both"/>
        <ActivatableClass ActivatableClassId="VideoEffects.SquareEffect" ThreadingModel="both"/>
      </InProcessServer>
    </Extension>
  </Extensions>

And my AppxManifest.xml 

<?xml version="1.0" encoding="utf-8"?>
<Package xmlns="http://schemas.microsoft.com/appx/2010/manifest" xmlns:m2="http://schemas.microsoft.com/appx/2013/manifest" xmlns:m3="http://schemas.microsoft.com/appx/2014/manifest" xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest" xmlns:build="http://schemas.microsoft.com/developer/appx/2012/build" IgnorableNamespaces="build">
  
  <Identity Name="c78898a7-1816-4706-8bfb-2f685c4aea88" Publisher="CN=anacorreia" Version="1.0.0.0" ProcessorArchitecture="arm" />
  <mp:PhoneIdentity PhoneProductId="c78898a7-1816-4706-8bfb-2f685c4aea88" PhonePublisherId="00000000-0000-0000-0000-000000000000" />
  <Properties>
    <DisplayName>App4.WindowsPhone</DisplayName>
    <PublisherDisplayName>anacorreia</PublisherDisplayName>
    <Logo>Assets\StoreLogo.png</Logo>
  </Properties>
  <Prerequisites>
    <OSMinVersion>6.3.1</OSMinVersion>
    <OSMaxVersionTested>6.3.1</OSMaxVersionTested>
  </Prerequisites>
  <Resources>
    <Resource Language="EN-US" />
  </Resources>
  <Applications>
    <Application Id="App" Executable="App4.WindowsPhone.exe" EntryPoint="App4.WindowsPhone.App">
      <m3:VisualElements DisplayName="App4.WindowsPhone" Square150x150Logo="Assets\Logo.png" Square44x44Logo="Assets\SmallLogo.png" Description="App4.WindowsPhone" ForegroundText="light" BackgroundColor="transparent">
        <m3:DefaultTile Wide310x150Logo="Assets\WideLogo.png" Square71x71Logo="Assets\Square71x71Logo.png" />
        <m3:SplashScreen Image="Assets\SplashScreen.png" />
      </m3:VisualElements>
    </Application>
  </Applications>
  <Capabilities>
    <Capability Name="internetClientServer" />
  </Capabilities>
  <Extensions>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>VideoEffects.WindowsPhone.dll</Path>
        <ActivatableClass ActivatableClassId="VideoEffects.CanvasEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="VideoEffects.LumiaEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="VideoEffects.LumiaAnalyzer" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="VideoEffects.ShaderEffectBgrx8" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="VideoEffects.ShaderEffectNv12" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="VideoEffects.SquareEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="VideoEffects.SquareEffectDefinition" ThreadingModel="both" />
      </InProcessServer>
    </Extension>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>CLRHost.dll</Path>
        <ActivatableClass ActivatableClassId="GoogleAnalytics.Core.TransactionItem" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="GoogleAnalytics.Core.PlatformInfoProvider" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="GoogleAnalytics.Core.Transaction" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="GoogleAnalytics.ProductReceipt" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="GoogleAnalytics.PlatformInfoProvider" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="GoogleAnalytics.EasyTrackerConfig" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="GoogleAnalytics.AppReceipt" ThreadingModel="both" />
      </InProcessServer>
    </Extension>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>Lumia.Imaging.dll</Path>
        <ActivatableClass ActivatableClassId="Lumia.Imaging.LinearGradient" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Version" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Compositing.ChromaKeyFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Compositing.AlphaToGrayscaleFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Compositing.InteractiveForegroundSegmenter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Compositing.BlendEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Compositing.BlendFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Compositing.ImageFusionFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Compositing.ObjectExtractor" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Transforms.RotationFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Transforms.ImageAligner" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Transforms.FlipFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Transforms.ScaleFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Transforms.CropFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Transforms.ReframingFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.CameraPreviewImageSource" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.CachingEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.AutoResizeConfiguration" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.BitmapRenderer" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.MoonlightFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.VignettingFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.SketchFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.WarpFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.SolarizeFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.FogFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.MonoColorFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.MirrorFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.SplitToneRange" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.MagicPenFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.StampFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.EmbossFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.LomoFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.WatercolorFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.FoundationFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.AntiqueFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.PaintFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.GrayscaleNegativeFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.MilkyFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.ColorSwapFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.SplitToneFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.NegativeFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.SepiaFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.CartoonFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.OilyFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.PosterizeFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Artistic.SpotlightFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.WhiteBalanceFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.Curve" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.VibranceFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.BrightnessFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.LensBlurPredefinedKernel" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.BlurFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.ColorAdjustFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.LensBlurCustomKernel" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.NoiseFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.CurvesFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.WhiteboardEnhancementFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.SaturationLightnessFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.DespeckleFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.HueSaturationLightnessFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.LensBlurEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.CurveMinMaxPair" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.RedEyeRemovalFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.RgbMixerFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.RgbLevelsFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.TemperatureAndTintFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.LocalBoostAutomaticFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.ContrastFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.AutoFixAnalyzer" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.LevelsFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.ColorBoostFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.AutoLevelsFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.AutoEnhanceFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.ColorizationFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.HueSaturationFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.SharpnessFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.GaussianNoiseFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.HdrEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.ArgbColorCurves" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.ExposureFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.GrayscaleFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.Adjustments.LocalBoostFilter" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.ImageProviderInfo" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.JpegRenderer" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.WriteableBitmapRenderer" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.GifRenderer" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.RenderRequest" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.RadialGradient" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Lumia.Imaging.FilterEffect" ThreadingModel="both" />
      </InProcessServer>
    </Extension>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>Lumia.InteropServices.WindowsRuntime.dll</Path>
        <ActivatableClass ActivatableClassId="Lumia.InteropServices.WindowsRuntime.BufferFactory" ThreadingModel="both" />
      </InProcessServer>
    </Extension>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>Microsoft.Graphics.Canvas.dll</Path>
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Geometry.CanvasStrokeStyle" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.ColorMatrixEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.ColorSourceEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.LinearTransferEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.SpotSpecularEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.ScaleEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.TurbulenceEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.BlendEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.AtlasEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.DirectionalBlurEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.LuminanceToAlphaEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.BorderEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.CropEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.Transform2DEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.DistantDiffuseEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.TileEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.Transform3DEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.DistantSpecularEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.ShadowEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.DisplacementMapEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.DpiCompensationEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.UnPremultiplyEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.DiscreteTransferEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.MorphologyEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.BrightnessEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.PointSpecularEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.GaussianBlurEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.GammaTransferEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.ConvolveMatrixEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.ArithmeticCompositeEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.SpotDiffuseEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.OpacityMetadataEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.PointDiffuseEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.SaturationEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.PremultiplyEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.CompositeEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.HueRotationEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Effects.TableTransferEffect" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.CanvasDevice" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.Text.CanvasTextFormat" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.UI.Xaml.CanvasAnimatedControl" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.UI.Xaml.CanvasControl" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="Microsoft.Graphics.Canvas.UI.Xaml.CanvasSwapChainPanel" ThreadingModel="both" />
      </InProcessServer>
    </Extension>
  </Extensions>
  <Dependencies>
    <PackageDependency Name="Microsoft.VCLibs.120.00.Phone.Debug" MinVersion="12.0.30113.0" />
  </Dependencies>
  <build:Metadata>
    <build:Item Name="SharedGUID" Value="72baf625-9470-423e-820f-9e7b5fe00e7d" />
    <build:Item Name="CodeSharingProject" Value="248F659F-DAC5-46E8-AC09-60EC9FC95053" />
    <build:Item Name="TargetFrameworkMoniker" Value="WindowsPhoneApp,Version=v8.1" />
    <build:Item Name="VisualStudio" Version="12.0" />
    <build:Item Name="VisualStudioEdition" Value="Microsoft Visual Studio Ultimate 2013" />
    <build:Item Name="OperatingSystem" Version="6.3.9600.16384 (winblue_rtm.130821-1623)" />
    <build:Item Name="Microsoft.Build.AppxPackage.dll" Version="12.0.31101.0" />
    <build:Item Name="ProjectGUID" Value="{5DB4E194-C8B9-4CC2-B19B-C056924B4855}" />
    <build:Item Name="Microsoft.Windows.UI.Xaml.Build.Tasks.dll" Version="12.0.30501.0" />
    <build:Item Name="MakePri.exe" Version="6.3.9600.17298 (winblue.141024-1500)" />
  </build:Metadata>
</Package>

**Comment by mmaitre314** [comment]
Did you try adding component registration explicitly in Package.appxmanifest?
```xml
<Extension Category="windows.activatableClass.inProcessServer">
  <InProcessServer>
    <Path>VideoEffects.Windows.dll</Path>
    <ActivatableClass ActivatableClassId="VideoEffects.CanvasEffect" ThreadingModel="both"/>
    <ActivatableClass ActivatableClassId="VideoEffects.LumiaEffect" ThreadingModel="both"/>
    <ActivatableClass ActivatableClassId="VideoEffects.LumiaAnalyzer" ThreadingModel="both"/>
    <ActivatableClass ActivatableClassId="VideoEffects.ShaderEffectBgrx8" ThreadingModel="both"/>
    <ActivatableClass ActivatableClassId="VideoEffects.ShaderEffectNv12" ThreadingModel="both"/>
    <ActivatableClass ActivatableClassId="VideoEffects.SquareEffect" ThreadingModel="both"/>
    <ActivatableClass ActivatableClassId="VideoEffects.LumiaEffectDefinition" ThreadingModel="both"/>
  </InProcessServer>
</Extension>
<Extension Category="windows.activatableClass.inProcessServer">
  <InProcessServer>
    <Path>Lumia.Imaging.dll</Path>
    <ActivatableClass ActivatableClassId="Lumia.Imaging.Bitmap" ThreadingModel="both" />
    <ActivatableClass ActivatableClassId="Lumia.Imaging.BitmapImageSource" ThreadingModel="both" />
  </InProcessServer>
</Extension>
```
(and similarly for Windows Phone)

**Comment by mmaitre314** [comment]
It's weird: I received an email from GitHub where it looked like you had copy/pasted some XML which got cut out. It does not show on the GitHub website. If you did, would you mind doing it again?

**Comment by LanceMcCarthy** [comment]
This is the strangest thing! I don't know what text was there or not, was it the missing ActivatibleClasses xml?



My github email is my work email because I have official repos to monitor (primarily the Telerik XAML doc and demos, but the Kendo UI ones as well).
Lance McCarthy | Tech Support Engineer, Sr.

________________________________
